name: pyobistools
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - pyworms
  - plotly
  - pandas
  - numpy
  - r-base
  - r-tidyverse
  - pip
  - pip:
      - git+https://github.com/cioos-siooc/pyobistools@main#egg=pyobistools
      - nest_asyncio
      - ipykernel
